// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: define.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SquickStruct {

  /// <summary>Holder for reflection information generated from define.proto</summary>
  public static partial class DefineReflection {

    #region Descriptor
    /// <summary>File descriptor for define.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxkZWZpbmUucHJvdG8SDFNxdWlja1N0cnVjdCqCBAoORUdhbWVFdmVudENv",
            "ZGUSCwoHU1VDQ0VTUxAAEhAKDFVOS09XTl9FUlJPUhABEhEKDUFDQ09VTlRf",
            "RVhJU1QQAhIWChJBQ0NPVU5UUFdEX0lOVkFMSUQQAxIRCg1BQ0NPVU5UX1VT",
            "SU5HEAQSEgoOQUNDT1VOVF9MT0NLRUQQBRIZChVBQ0NPVU5UX0xPR0lOX1NV",
            "Q0NFU1MQBhIWChJWRVJJRllfS0VZX1NVQ0NFU1MQBxITCg9WRVJJRllfS0VZ",
            "X0ZBSUwQCBIYChRTRUxFQ1RTRVJWRVJfU1VDQ0VTUxAJEhUKEVNFTEVDVFNF",
            "UlZFUl9GQUlMEAoSEwoPQ0hBUkFDVEVSX0VYSVNUEG4SFQoRU1ZSWk9ORUlE",
            "X0lOVkFMSUQQbxIUChBDSEFSQUNURVJfTlVNT1VUEHASFQoRQ0hBUkFDVEVS",
            "X0lOVkFMSUQQcRIWChJDSEFSQUNURVJfTk9URVhJU1QQchITCg9DSEFSQUNU",
            "RVJfVVNJTkcQcxIUChBDSEFSQUNURVJfTE9DS0VEEHQSEQoNWk9ORV9PVkVS",
            "TE9BRBB1Eg4KCk5PVF9PTkxJTkUQdhIZChRJTlNVRkZJQ0lFTlRfRElBTU9O",
            "RBDIARIWChFJTlNVRkZJQ0lFTlRfR09MRBDJARIUCg9JTlNVRkZJQ0lFTlRf",
            "U1AQygEq0QkKC1NlcnZlck1zZ0lkEhYKElNFUlZFUl9NU0dfSURfTk9ORRAA",
            "Eh4KGldPUkxEX1RPX01BU1RFUl9SRUdJU1RFUkVEEAESIAocV09STERfVE9f",
            "TUFTVEVSX1VOUkVHSVNURVJFRBACEhsKF1dPUkxEX1RPX01BU1RFUl9SRUZS",
            "RVNIEAMSHgoaTE9HSU5fVE9fTUFTVEVSX1JFR0lTVEVSRUQQBBIgChxMT0dJ",
            "Tl9UT19NQVNURVJfVU5SRUdJU1RFUkVEEAUSGwoXTE9HSU5fVE9fTUFTVEVS",
            "X1JFRlJFU0gQBhIdChlQUk9YWV9UT19XT1JMRF9SRUdJU1RFUkVEEAcSHwob",
            "UFJPWFlfVE9fV09STERfVU5SRUdJU1RFUkVEEAgSGgoWUFJPWFlfVE9fV09S",
            "TERfUkVGUkVTSBAJEhwKGFBST1hZX1RPX0dBTUVfUkVHSVNURVJFRBAKEh4K",
            "GlBST1hZX1RPX0dBTUVfVU5SRUdJU1RFUkVEEAsSGQoVUFJPWFlfVE9fR0FN",
            "RV9SRUZSRVNIEAwSHAoYR0FNRV9UT19XT1JMRF9SRUdJU1RFUkVEEA0SHgoa",
            "R0FNRV9UT19XT1JMRF9VTlJFR0lTVEVSRUQQDhIZChVHQU1FX1RPX1dPUkxE",
            "X1JFRlJFU0gQDxIaChZEQl9UT19XT1JMRF9SRUdJU1RFUkVEEBASHAoYREJf",
            "VE9fV09STERfVU5SRUdJU1RFUkVEEBESFwoTREJfVE9fV09STERfUkVGUkVT",
            "SBASEiMKH1BWUF9NQU5BR0VSX1RPX1dPUkxEX1JFR0lTVEVSRUQQExIlCiFQ",
            "VlBfTUFOQUdFUl9UT19XT1JMRF9VTlJFR0lTVEVSRUQQFBIgChxQVlBfTUFO",
            "QUdFUl9UT19XT1JMRF9SRUZSRVNIEBUSIgoeUFZQX01BTkFHRVJfVE9fR0FN",
            "RV9SRUdJU1RFUkVEEBYSJAogUFZQX01BTkFHRVJfVE9fR0FNRV9VTlJFR0lT",
            "VEVSRUQQFxIfChtQVlBfTUFOQUdFUl9UT19HQU1FX1JFRlJFU0gQGBIbChdS",
            "RVFfUFZQX0lOU1RBTkNFX0NSRUFURRAeEhsKF0FDS19QVlBfSU5TVEFOQ0Vf",
            "Q1JFQVRFEB8SHAoYUkVRX1BWUF9JTlNUQU5DRV9ERVNUUk9ZECASHAoYQUNL",
            "X1BWUF9JTlNUQU5DRV9ERVNUUk9ZECESGwoXUkVRX1BWUF9JTlNUQU5DRV9T",
            "VEFUVVMQIhIbChdBQ0tfUFZQX0lOU1RBTkNFX1NUQVRVUxAjEhkKFVJFUV9Q",
            "VlBfSU5TVEFOQ0VfTElTVBAkEhkKFUFDS19QVlBfSU5TVEFOQ0VfTElTVBAl",
            "EhIKDlJFUV9QVlBfU1RBVFVTEDISEgoOQUNLX1BWUF9TVEFUVVMQMxIVChFS",
            "RVFfUFZQX0dBTUVfSU5JVBA0EhUKEUFDS19QVlBfR0FNRV9JTklUEDUSEwoP",
            "UkVRX1BMQVlFUl9JTkZPEDYSEwoPQUNLX1BMQVlFUl9JTkZPEDcSEgoOQUNL",
            "X05FV19QTEFZRVIQOBIbChdSRVFfQ09OTkVDVF9HQU1FX1NFUlZFUhA8EhsK",
            "F0FDS19DT05ORUNUX0dBTUVfU0VSVkVSED0q7REKCkVHYW1lTXNnSUQSCgoG",
            "VU5LTk9XEAASEAoMRVZFTlRfUkVTVUxUEAESEwoPRVZFTlRfVFJBTlNQT1JU",
            "EAISEAoMQ0xPU0VfU09DS0VUEAMSEAoMU1RTX05FVF9JTkZPEEYSEAoMUkVR",
            "X0xBR19URVNUEFASFQoRQUNLX0dBVEVfTEFHX1RFU1QQURIVChFBQ0tfR0FN",
            "RV9MQUdfVEVTVBBSEhUKEVNUU19TRVJWRVJfUkVQT1JUEFoSEgoOU1RTX0hF",
            "QVJUX0JFQVQQZBINCglSRVFfTE9HSU4QZRINCglBQ0tfTE9HSU4QZhIOCgpS",
            "RVFfTE9HT1VUEGcSEgoOUkVRX1dPUkxEX0xJU1QQbhISCg5BQ0tfV09STERf",
            "TElTVBBvEhUKEVJFUV9DT05ORUNUX1dPUkxEEHASFQoRQUNLX0NPTk5FQ1Rf",
            "V09STEQQcRIZChVSRVFfS0lDS0VEX0ZST01fV09STEQQchITCg9SRVFfQ09O",
            "TkVDVF9LRVkQeBITCg9BQ0tfQ09OTkVDVF9LRVkQehIWChFSRVFfU0VMRUNU",
            "X1NFUlZFUhCCARIWChFBQ0tfU0VMRUNUX1NFUlZFUhCDARISCg1SRVFfUk9M",
            "RV9MSVNUEIQBEhIKDUFDS19ST0xFX0xJU1QQhQESFAoPUkVRX0NSRUFURV9S",
            "T0xFEIYBEhQKD1JFUV9ERUxFVEVfUk9MRRCHARIVChBSRVFfUkVDT1ZFUl9S",
            "T0xFEIgBEhcKElJFUV9MT0FEX1JPTEVfREFUQRCMARIXChJBQ0tfTE9BRF9S",
            "T0xFX0RBVEEQjQESFwoSUkVRX1NBVkVfUk9MRV9EQVRBEI4BEhcKEkFDS19T",
            "QVZFX1JPTEVfREFUQRCPARITCg5SRVFfRU5URVJfR0FNRRCWARITCg5BQ0tf",
            "RU5URVJfR0FNRRCXARITCg5SRVFfTEVBVkVfR0FNRRCYARITCg5BQ0tfTEVB",
            "VkVfR0FNRRCZARIaChVSRVFfRU5URVJfR0FNRV9GSU5JU0gQmgESGgoVQUNL",
            "X0VOVEVSX0dBTUVfRklOSVNIEJsBEhQKD1JFUV9FTlRFUl9TQ0VORRCgARIU",
            "Cg9BQ0tfRU5URVJfU0NFTkUQoQESFAoPUkVRX0xFQVZFX1NDRU5FEKIBEhQK",
            "D0FDS19MRUFWRV9TQ0VORRCjARIbChZSRVFfRU5URVJfU0NFTkVfRklOSVNI",
            "EKQBEhsKFkFDS19FTlRFUl9TQ0VORV9GSU5JU0gQpQESEwoOUkVRX1NXQVBf",
            "U0NFTkUQqgESEwoOQUNLX1NXQVBfU0NFTkUQqwESGAoTUkVRX1NXQVBfSE9N",
            "RV9TQ0VORRCsARIYChNBQ0tfU1dBUF9IT01FX1NDRU5FEK0BEhUKEEFDS19P",
            "QkpFQ1RfRU5UUlkQyAESFQoQQUNLX09CSkVDVF9MRUFWRRDJARIeChlBQ0tf",
            "T0JKRUNUX1BST1BFUlRZX0VOVFJZEMoBEhwKF0FDS19PQkpFQ1RfUkVDT1JE",
            "X0VOVFJZEMsBEhUKEEFDS19QUk9QRVJUWV9JTlQQ0gESFwoSQUNLX1BST1BF",
            "UlRZX0ZMT0FUENMBEhgKE0FDS19QUk9QRVJUWV9TVFJJTkcQ1AESGAoTQUNL",
            "X1BST1BFUlRZX09CSkVDVBDWARIZChRBQ0tfUFJPUEVSVFlfVkVDVE9SMhDX",
            "ARIZChRBQ0tfUFJPUEVSVFlfVkVDVE9SMxDYARIXChJBQ0tfUFJPUEVSVFlf",
            "Q0xFQVIQ2QESEAoLQUNLX0FERF9ST1cQ3AESEwoOQUNLX1JFTU9WRV9ST1cQ",
            "3QESEQoMQUNLX1NXQVBfUk9XEN4BEhMKDkFDS19SRUNPUkRfSU5UEN8BEhUK",
            "EEFDS19SRUNPUkRfRkxPQVQQ4AESFgoRQUNLX1JFQ09SRF9TVFJJTkcQ4gES",
            "FgoRQUNLX1JFQ09SRF9PQkpFQ1QQ4wESFwoSQUNLX1JFQ09SRF9WRUNUT1Iy",
            "EOQBEhcKEkFDS19SRUNPUkRfVkVDVE9SMxDlARIVChBBQ0tfUkVDT1JEX0NM",
            "RUFSEPoBEhQKD0FDS19SRUNPUkRfU09SVBD7ARIWChFBQ0tfREFUQV9GSU5J",
            "U0hFRBCEAhINCghSRVFfTU9WRRCsAhINCghBQ0tfTU9WRRCtAhINCghSRVFf",
            "Q0hBVBDeAhINCghBQ0tfQ0hBVBDfAhIWChFSRVFfU0tJTExfT0JKRUNUWBCQ",
            "AxIWChFBQ0tfU0tJTExfT0JKRUNUWBCRAxISCg1SRVFfU0tJTExfUE9TEJID",
            "EhIKDUFDS19TS0lMTF9QT1MQkwMSFgoRQUNLX09OTElORV9OT1RJRlkQ2AQS",
            "FwoSQUNLX09GRkxJTkVfTk9USUZZENkEEhQKD1JFUV9ST09NX0NSRUFURRDo",
            "BxIUCg9BQ0tfUk9PTV9DUkVBVEUQ6QcSFQoQUkVRX1JPT01fREVUQUlMUxDq",
            "BxIVChBBQ0tfUk9PTV9ERVRBSUxTEOsHEhIKDVJFUV9ST09NX0pPSU4Q7AcS",
            "EgoNQUNLX1JPT01fSk9JThDtBxIZChRBQ0tfUk9PTV9KT0lOX05PVElDRRDu",
            "BxISCg1SRVFfUk9PTV9RVUlUEO8HEhIKDUFDS19ST09NX1FVSVQQ8AcSGQoU",
            "QUNLX1JPT01fUVVJVF9OT1RJQ0UQ8QcSEgoNUkVRX1JPT01fTElTVBDyBxIS",
            "Cg1BQ0tfUk9PTV9MSVNUEPMHEhoKFVJFUV9ST09NX1BMQVlFUl9FVkVOVBD8",
            "BxIaChVBQ0tfUk9PTV9QTEFZRVJfRVZFTlQQ/QcSFwoSUkVRX1NUQVJUX1BW",
            "UF9HQU1FEIgIEhcKEkFDS19TVEFSVF9QVlBfR0FNRRCJCBIWChFSRVFfSk9J",
            "Tl9QVlBfR0FNRRCKCBIWChFBQ0tfSk9JTl9QVlBfR0FNRRCLCBIWChFSRVFf",
            "UVVJVF9QVlBfR0FNRRCMCBIWChFBQ0tfUVVJVF9QVlBfR0FNRRCNCBIWChFB",
            "Q0tfUFZQX0dBTUVfT1ZFUhCOCCpHCglFSXRlbVR5cGUSDQoJRUlUX0VRVUlQ",
            "EAASCwoHRUlUX0dFTRABEg4KCkVJVF9TVVBQTFkQAhIOCgpFSVRfU0NST0xM",
            "EAMqtwEKCkVTa2lsbFR5cGUSFgoSQlJJRUZfU0lOR0xFX1NLSUxMEAASFQoR",
            "QlJJRUZfR1JPVVBfU0tJTEwQARIXChNCVUxMRVRfU0lOR0xFX1NLSUxMEAIS",
            "GAoUQlVMTEVUX1JFQk9VTkRfU0tJTEwQAxIcChhCVUxMRVRfVEFSR0VUX0JP",
            "TUJfU0tJTEwQBBIZChVCVUxMRVRfUE9TX0JPTUJfU0tJTEwQBRIOCgpGVU5D",
            "X1NLSUxMEAYqTQoKRVNjZW5lVHlwZRIQCgxOT1JNQUxfU0NFTkUQABIWChJT",
            "SU5HTEVfQ0xPTkVfU0NFTkUQARIVChFNVUxUSV9DTE9ORV9TQ0VORRACKkYK",
            "CEVOUENUeXBlEg4KCk5PUk1BTF9OUEMQABIMCghIRVJPX05QQxABEg4KClRV",
            "UlJFVF9OUEMQAhIMCghGVU5DX05QQxADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SquickStruct.EGameEventCode), typeof(global::SquickStruct.ServerMsgId), typeof(global::SquickStruct.EGameMsgID), typeof(global::SquickStruct.EItemType), typeof(global::SquickStruct.ESkillType), typeof(global::SquickStruct.ESceneType), typeof(global::SquickStruct.ENPCType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///events
  /// </summary>
  public enum EGameEventCode {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("UNKOWN_ERROR")] UnkownError = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_EXIST")] AccountExist = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNTPWD_INVALID")] AccountpwdInvalid = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_USING")] AccountUsing = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_LOCKED")] AccountLocked = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_LOGIN_SUCCESS")] AccountLoginSuccess = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("VERIFY_KEY_SUCCESS")] VerifyKeySuccess = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("VERIFY_KEY_FAIL")] VerifyKeyFail = 8,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SELECTSERVER_SUCCESS")] SelectserverSuccess = 9,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SELECTSERVER_FAIL")] SelectserverFail = 10,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_EXIST")] CharacterExist = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SVRZONEID_INVALID")] SvrzoneidInvalid = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_NUMOUT")] CharacterNumout = 112,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_INVALID")] CharacterInvalid = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_NOTEXIST")] CharacterNotexist = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_USING")] CharacterUsing = 115,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_LOCKED")] CharacterLocked = 116,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ZONE_OVERLOAD")] ZoneOverload = 117,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("NOT_ONLINE")] NotOnline = 118,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("INSUFFICIENT_DIAMOND")] InsufficientDiamond = 200,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("INSUFFICIENT_GOLD")] InsufficientGold = 201,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("INSUFFICIENT_SP")] InsufficientSp = 202,
  }

  /// <summary>
  /// Servers RPC 
  /// </summary>
  public enum ServerMsgId {
    [pbr::OriginalName("SERVER_MSG_ID_NONE")] None = 0,
    [pbr::OriginalName("WORLD_TO_MASTER_REGISTERED")] WorldToMasterRegistered = 1,
    [pbr::OriginalName("WORLD_TO_MASTER_UNREGISTERED")] WorldToMasterUnregistered = 2,
    [pbr::OriginalName("WORLD_TO_MASTER_REFRESH")] WorldToMasterRefresh = 3,
    [pbr::OriginalName("LOGIN_TO_MASTER_REGISTERED")] LoginToMasterRegistered = 4,
    [pbr::OriginalName("LOGIN_TO_MASTER_UNREGISTERED")] LoginToMasterUnregistered = 5,
    [pbr::OriginalName("LOGIN_TO_MASTER_REFRESH")] LoginToMasterRefresh = 6,
    [pbr::OriginalName("PROXY_TO_WORLD_REGISTERED")] ProxyToWorldRegistered = 7,
    [pbr::OriginalName("PROXY_TO_WORLD_UNREGISTERED")] ProxyToWorldUnregistered = 8,
    [pbr::OriginalName("PROXY_TO_WORLD_REFRESH")] ProxyToWorldRefresh = 9,
    [pbr::OriginalName("PROXY_TO_GAME_REGISTERED")] ProxyToGameRegistered = 10,
    [pbr::OriginalName("PROXY_TO_GAME_UNREGISTERED")] ProxyToGameUnregistered = 11,
    [pbr::OriginalName("PROXY_TO_GAME_REFRESH")] ProxyToGameRefresh = 12,
    [pbr::OriginalName("GAME_TO_WORLD_REGISTERED")] GameToWorldRegistered = 13,
    [pbr::OriginalName("GAME_TO_WORLD_UNREGISTERED")] GameToWorldUnregistered = 14,
    [pbr::OriginalName("GAME_TO_WORLD_REFRESH")] GameToWorldRefresh = 15,
    [pbr::OriginalName("DB_TO_WORLD_REGISTERED")] DbToWorldRegistered = 16,
    [pbr::OriginalName("DB_TO_WORLD_UNREGISTERED")] DbToWorldUnregistered = 17,
    [pbr::OriginalName("DB_TO_WORLD_REFRESH")] DbToWorldRefresh = 18,
    /// <summary>
    /// 将PVP管理服务器注册到 World 服务器
    /// </summary>
    [pbr::OriginalName("PVP_MANAGER_TO_WORLD_REGISTERED")] PvpManagerToWorldRegistered = 19,
    [pbr::OriginalName("PVP_MANAGER_TO_WORLD_UNREGISTERED")] PvpManagerToWorldUnregistered = 20,
    [pbr::OriginalName("PVP_MANAGER_TO_WORLD_REFRESH")] PvpManagerToWorldRefresh = 21,
    /// <summary>
    /// 将PVP管理服务器注册到 GAME 服务器, PVP Manager
    /// </summary>
    [pbr::OriginalName("PVP_MANAGER_TO_GAME_REGISTERED")] PvpManagerToGameRegistered = 22,
    [pbr::OriginalName("PVP_MANAGER_TO_GAME_UNREGISTERED")] PvpManagerToGameUnregistered = 23,
    [pbr::OriginalName("PVP_MANAGER_TO_GAME_REFRESH")] PvpManagerToGameRefresh = 24,
    /// <summary>
    /// Pvp Manager API
    /// PVP 管理服 接口
    /// </summary>
    [pbr::OriginalName("REQ_PVP_INSTANCE_CREATE")] ReqPvpInstanceCreate = 30,
    [pbr::OriginalName("ACK_PVP_INSTANCE_CREATE")] AckPvpInstanceCreate = 31,
    [pbr::OriginalName("REQ_PVP_INSTANCE_DESTROY")] ReqPvpInstanceDestroy = 32,
    [pbr::OriginalName("ACK_PVP_INSTANCE_DESTROY")] AckPvpInstanceDestroy = 33,
    [pbr::OriginalName("REQ_PVP_INSTANCE_STATUS")] ReqPvpInstanceStatus = 34,
    [pbr::OriginalName("ACK_PVP_INSTANCE_STATUS")] AckPvpInstanceStatus = 35,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("REQ_PVP_INSTANCE_LIST")] ReqPvpInstanceList = 36,
    [pbr::OriginalName("ACK_PVP_INSTANCE_LIST")] AckPvpInstanceList = 37,
    /// <summary>
    /// Pvp Manager API
    /// PVP 接口, 由PVP -> PVP Manager -> Game
    /// 在PVP游戏中，以Game服务器为主，PVP服务器只负责当前对局网络同步和数据结算，不做其他逻辑功能
    /// </summary>
    [pbr::OriginalName("REQ_PVP_STATUS")] ReqPvpStatus = 50,
    [pbr::OriginalName("ACK_PVP_STATUS")] AckPvpStatus = 51,
    /// <summary>
    /// 创建完毕PVP服务器后， PVP服务器向Game服务器初始化对战服数据和各玩家数据
    /// </summary>
    [pbr::OriginalName("REQ_PVP_GAME_INIT")] ReqPvpGameInit = 52,
    [pbr::OriginalName("ACK_PVP_GAME_INIT")] AckPvpGameInit = 53,
    /// <summary>
    /// 加入玩家，
    /// </summary>
    [pbr::OriginalName("REQ_PLAYER_INFO")] ReqPlayerInfo = 54,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_PLAYER_INFO")] AckPlayerInfo = 55,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_NEW_PLAYER")] AckNewPlayer = 56,
    /// <summary>
    /// PVP请求连接Game Server
    /// </summary>
    [pbr::OriginalName("REQ_CONNECT_GAME_SERVER")] ReqConnectGameServer = 60,
    [pbr::OriginalName("ACK_CONNECT_GAME_SERVER")] AckConnectGameServer = 61,
  }

  /// <summary>
  /// Client RPC 
  /// </summary>
  public enum EGameMsgID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("UNKNOW")] Unknow = 0,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EVENT_RESULT")] EventResult = 1,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EVENT_TRANSPORT")] EventTransport = 2,
    /// <summary>
    /// want to close some one
    /// </summary>
    [pbr::OriginalName("CLOSE_SOCKET")] CloseSocket = 3,
    [pbr::OriginalName("STS_NET_INFO")] StsNetInfo = 70,
    /// <summary>
    /// LAG_TEST
    /// </summary>
    [pbr::OriginalName("REQ_LAG_TEST")] ReqLagTest = 80,
    /// <summary>
    /// 代理服务器响应
    /// </summary>
    [pbr::OriginalName("ACK_GATE_LAG_TEST")] AckGateLagTest = 81,
    /// <summary>
    /// 游戏服务器响应
    /// </summary>
    [pbr::OriginalName("ACK_GAME_LAG_TEST")] AckGameLagTest = 82,
    /// <summary>
    /// 服务端报告服务状态
    /// </summary>
    [pbr::OriginalName("STS_SERVER_REPORT")] StsServerReport = 90,
    /// <summary>
    /// 服务端之间心跳包
    /// </summary>
    [pbr::OriginalName("STS_HEART_BEAT")] StsHeartBeat = 100,
    /// <summary>
    ///////////////////////////////////////////////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("REQ_LOGIN")] ReqLogin = 101,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LOGIN")] AckLogin = 102,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LOGOUT")] ReqLogout = 103,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_WORLD_LIST")] ReqWorldList = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_WORLD_LIST")] AckWorldList = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CONNECT_WORLD")] ReqConnectWorld = 112,
    [pbr::OriginalName("ACK_CONNECT_WORLD")] AckConnectWorld = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_KICKED_FROM_WORLD")] ReqKickedFromWorld = 114,
    /// <summary>
    /// 先获取  Connect key 才能建立连接
    /// </summary>
    [pbr::OriginalName("REQ_CONNECT_KEY")] ReqConnectKey = 120,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_CONNECT_KEY")] AckConnectKey = 122,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SELECT_SERVER")] ReqSelectServer = 130,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SELECT_SERVER")] AckSelectServer = 131,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ROLE_LIST")] ReqRoleList = 132,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ROLE_LIST")] AckRoleList = 133,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CREATE_ROLE")] ReqCreateRole = 134,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_DELETE_ROLE")] ReqDeleteRole = 135,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_RECOVER_ROLE")] ReqRecoverRole = 136,
    /// <summary>
    /// 加载玩家数据
    /// </summary>
    [pbr::OriginalName("REQ_LOAD_ROLE_DATA")] ReqLoadRoleData = 140,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LOAD_ROLE_DATA")] AckLoadRoleData = 141,
    /// <summary>
    /// 请求保存玩家数据
    /// </summary>
    [pbr::OriginalName("REQ_SAVE_ROLE_DATA")] ReqSaveRoleData = 142,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_SAVE_ROLE_DATA")] AckSaveRoleData = 143,
    /// <summary>
    /// 进入游戏
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_GAME")] ReqEnterGame = 150,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_ENTER_GAME")] AckEnterGame = 151,
    /// <summary>
    /// 离开游戏
    /// </summary>
    [pbr::OriginalName("REQ_LEAVE_GAME")] ReqLeaveGame = 152,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_LEAVE_GAME")] AckLeaveGame = 153,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_GAME_FINISH")] ReqEnterGameFinish = 154,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ENTER_GAME_FINISH")] AckEnterGameFinish = 155,
    /// <summary>
    /// 请求加入场景
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_SCENE")] ReqEnterScene = 160,
    [pbr::OriginalName("ACK_ENTER_SCENE")] AckEnterScene = 161,
    /// <summary>
    /// 离开场景
    /// </summary>
    [pbr::OriginalName("REQ_LEAVE_SCENE")] ReqLeaveScene = 162,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_LEAVE_SCENE")] AckLeaveScene = 163,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_SCENE_FINISH")] ReqEnterSceneFinish = 164,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ENTER_SCENE_FINISH")] AckEnterSceneFinish = 165,
    /// <summary>
    /// 切换场景
    /// </summary>
    [pbr::OriginalName("REQ_SWAP_SCENE")] ReqSwapScene = 170,
    /// <summary>
    ///  
    /// </summary>
    [pbr::OriginalName("ACK_SWAP_SCENE")] AckSwapScene = 171,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("REQ_SWAP_HOME_SCENE")] ReqSwapHomeScene = 172,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_SWAP_HOME_SCENE")] AckSwapHomeScene = 173,
    /// <summary>
    /// 场景对象
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_ENTRY")] AckObjectEntry = 200,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_LEAVE")] AckObjectLeave = 201,
    /// <summary>
    /// 对象属性
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_PROPERTY_ENTRY")] AckObjectPropertyEntry = 202,
    /// <summary>
    /// 对象记录值
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_RECORD_ENTRY")] AckObjectRecordEntry = 203,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_INT")] AckPropertyInt = 210,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_FLOAT")] AckPropertyFloat = 211,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_STRING")] AckPropertyString = 212,
    /// <summary>
    ///EGMI_ACK_PROPERTY_DOUBLE				= 213;			//
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_OBJECT")] AckPropertyObject = 214,
    [pbr::OriginalName("ACK_PROPERTY_VECTOR2")] AckPropertyVector2 = 215,
    [pbr::OriginalName("ACK_PROPERTY_VECTOR3")] AckPropertyVector3 = 216,
    /// <summary>
    /// 属性清除
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_CLEAR")] AckPropertyClear = 217,
    [pbr::OriginalName("ACK_ADD_ROW")] AckAddRow = 220,
    [pbr::OriginalName("ACK_REMOVE_ROW")] AckRemoveRow = 221,
    [pbr::OriginalName("ACK_SWAP_ROW")] AckSwapRow = 222,
    [pbr::OriginalName("ACK_RECORD_INT")] AckRecordInt = 223,
    [pbr::OriginalName("ACK_RECORD_FLOAT")] AckRecordFloat = 224,
    /// <summary>
    ///EGMI_ACK_RECORD_DOUBLE				= 225;
    /// </summary>
    [pbr::OriginalName("ACK_RECORD_STRING")] AckRecordString = 226,
    [pbr::OriginalName("ACK_RECORD_OBJECT")] AckRecordObject = 227,
    [pbr::OriginalName("ACK_RECORD_VECTOR2")] AckRecordVector2 = 228,
    [pbr::OriginalName("ACK_RECORD_VECTOR3")] AckRecordVector3 = 229,
    /// <summary>
    /// 记录值清除
    /// </summary>
    [pbr::OriginalName("ACK_RECORD_CLEAR")] AckRecordClear = 250,
    [pbr::OriginalName("ACK_RECORD_SORT")] AckRecordSort = 251,
    /// <summary>
    /// 服务端发送对象数据完成
    /// </summary>
    [pbr::OriginalName("ACK_DATA_FINISHED")] AckDataFinished = 260,
    [pbr::OriginalName("REQ_MOVE")] ReqMove = 300,
    /// <summary>
    /// 移动
    /// </summary>
    [pbr::OriginalName("ACK_MOVE")] AckMove = 301,
    [pbr::OriginalName("REQ_CHAT")] ReqChat = 350,
    [pbr::OriginalName("ACK_CHAT")] AckChat = 351,
    [pbr::OriginalName("REQ_SKILL_OBJECTX")] ReqSkillObjectx = 400,
    [pbr::OriginalName("ACK_SKILL_OBJECTX")] AckSkillObjectx = 401,
    [pbr::OriginalName("REQ_SKILL_POS")] ReqSkillPos = 402,
    [pbr::OriginalName("ACK_SKILL_POS")] AckSkillPos = 403,
    [pbr::OriginalName("ACK_ONLINE_NOTIFY")] AckOnlineNotify = 600,
    [pbr::OriginalName("ACK_OFFLINE_NOTIFY")] AckOfflineNotify = 601,
    /// <summary>
    /// 玩家房间逻辑
    /// </summary>
    [pbr::OriginalName("REQ_ROOM_CREATE")] ReqRoomCreate = 1000,
    [pbr::OriginalName("ACK_ROOM_CREATE")] AckRoomCreate = 1001,
    [pbr::OriginalName("REQ_ROOM_DETAILS")] ReqRoomDetails = 1002,
    [pbr::OriginalName("ACK_ROOM_DETAILS")] AckRoomDetails = 1003,
    [pbr::OriginalName("REQ_ROOM_JOIN")] ReqRoomJoin = 1004,
    [pbr::OriginalName("ACK_ROOM_JOIN")] AckRoomJoin = 1005,
    [pbr::OriginalName("ACK_ROOM_JOIN_NOTICE")] AckRoomJoinNotice = 1006,
    /// <summary>
    /// 离开房间
    /// </summary>
    [pbr::OriginalName("REQ_ROOM_QUIT")] ReqRoomQuit = 1007,
    [pbr::OriginalName("ACK_ROOM_QUIT")] AckRoomQuit = 1008,
    [pbr::OriginalName("ACK_ROOM_QUIT_NOTICE")] AckRoomQuitNotice = 1009,
    /// <summary>
    /// 获取房间列表
    /// </summary>
    [pbr::OriginalName("REQ_ROOM_LIST")] ReqRoomList = 1010,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_ROOM_LIST")] AckRoomList = 1011,
    /// <summary>
    /// 在房间里互动以及事件，广播形式发送给房间内所有玩家
    /// </summary>
    [pbr::OriginalName("REQ_ROOM_PLAYER_EVENT")] ReqRoomPlayerEvent = 1020,
    [pbr::OriginalName("ACK_ROOM_PLAYER_EVENT")] AckRoomPlayerEvent = 1021,
    /// <summary>
    /// 对战逻辑
    /// </summary>
    [pbr::OriginalName("REQ_START_PVP_GAME")] ReqStartPvpGame = 1032,
    [pbr::OriginalName("ACK_START_PVP_GAME")] AckStartPvpGame = 1033,
    /// <summary>
    /// 请求加入对战中的游戏
    /// </summary>
    [pbr::OriginalName("REQ_JOIN_PVP_GAME")] ReqJoinPvpGame = 1034,
    [pbr::OriginalName("ACK_JOIN_PVP_GAME")] AckJoinPvpGame = 1035,
    /// <summary>
    /// 玩家请求退出当前对局，由 Player -> Proxy -> Game -> PvpManager -> Pvp
    /// </summary>
    [pbr::OriginalName("REQ_QUIT_PVP_GAME")] ReqQuitPvpGame = 1036,
    [pbr::OriginalName("ACK_QUIT_PVP_GAME")] AckQuitPvpGame = 1037,
    /// <summary>
    /// 游戏结束
    /// </summary>
    [pbr::OriginalName("ACK_PVP_GAME_OVER")] AckPvpGameOver = 1038,
  }

  public enum EItemType {
    /// <summary>
    ///the equipment which can add props
    /// </summary>
    [pbr::OriginalName("EIT_EQUIP")] EitEquip = 0,
    /// <summary>
    ///the gem ca be embed to the equipment
    /// </summary>
    [pbr::OriginalName("EIT_GEM")] EitGem = 1,
    /// <summary>
    ///expendable items for player, such as a medicine that cures
    /// </summary>
    [pbr::OriginalName("EIT_SUPPLY")] EitSupply = 2,
    /// <summary>
    ///special items that can call a hero or others, special items can do what you want to do
    /// </summary>
    [pbr::OriginalName("EIT_SCROLL")] EitScroll = 3,
  }

  public enum ESkillType {
    /// <summary>
    ///this kind of skill just can damage one object
    /// </summary>
    [pbr::OriginalName("BRIEF_SINGLE_SKILL")] BriefSingleSkill = 0,
    /// <summary>
    ///this kind of skill can damage multiple objects
    /// </summary>
    [pbr::OriginalName("BRIEF_GROUP_SKILL")] BriefGroupSkill = 1,
    /// <summary>
    ///this kind of bullet just can damage one object
    /// </summary>
    [pbr::OriginalName("BULLET_SINGLE_SKILL")] BulletSingleSkill = 2,
    /// <summary>
    ///this kind of bullet can damage multiple objects via rebound
    /// </summary>
    [pbr::OriginalName("BULLET_REBOUND_SKILL")] BulletReboundSkill = 3,
    /// <summary>
    ///this kind of bullet can damage multiple objects who around the target when the bullet touched the target object
    /// </summary>
    [pbr::OriginalName("BULLET_TARGET_BOMB_SKILL")] BulletTargetBombSkill = 4,
    /// <summary>
    ///this kind of bullet can damage multiple objects  who around the target when the bullet arrived the position
    /// </summary>
    [pbr::OriginalName("BULLET_POS_BOMB_SKILL")] BulletPosBombSkill = 5,
    [pbr::OriginalName("FUNC_SKILL")] FuncSkill = 6,
  }

  /// <summary>
  /// 场景形式，玩家进入后，自己开一个独立场景
  /// </summary>
  public enum ESceneType {
    /// <summary>
    ///public town, only has one group available for players is 1
    /// </summary>
    [pbr::OriginalName("NORMAL_SCENE")] NormalScene = 0,
    /// <summary>
    ///private room, only has one player per group and it will be destroyed if the player leaved from group.
    /// </summary>
    [pbr::OriginalName("SINGLE_CLONE_SCENE")] SingleCloneScene = 1,
    /// <summary>
    ///private room, only has more than one player per group and it will be destroyed if all players leaved from group.
    /// </summary>
    [pbr::OriginalName("MULTI_CLONE_SCENE")] MultiCloneScene = 2,
  }

  public enum ENPCType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("NORMAL_NPC")] NormalNpc = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("HERO_NPC")] HeroNpc = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TURRET_NPC")] TurretNpc = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("FUNC_NPC")] FuncNpc = 3,
  }

  #endregion

}

#endregion Designer generated code
