----------------------------------------------------------------------------------
-- don't edit it, generated from .proto files by tools
----------------------------------------------------------------------------------

EGameCommandType = {
  EGCT_MODIY_PROPERTY = 0, EGCT_MODIY_ITEM = 1, EGCT_CREATE_OBJECT = 2, EGCT_ADD_ROLE_EXP = 3, 
}

EGameEventCode = {
  SUCCESS = 0, UNKOWN_ERROR = 1, ACCOUNT_EXIST = 2, ACCOUNTPWD_INVALID = 3, ACCOUNT_USING = 4, 
  ACCOUNT_LOCKED = 5, ACCOUNT_LOGIN_SUCCESS = 6, VERIFY_KEY_SUCCESS = 7, VERIFY_KEY_FAIL = 8, 
  SELECTSERVER_SUCCESS = 9, SELECTSERVER_FAIL = 10, CHARACTER_EXIST = 110, 
  SVRZONEID_INVALID = 111, CHARACTER_NUMOUT = 112, CHARACTER_INVALID = 113, 
  CHARACTER_NOTEXIST = 114, CHARACTER_USING = 115, CHARACTER_LOCKED = 116, ZONE_OVERLOAD = 117, 
  NOT_ONLINE = 118, INSUFFICIENT_DIAMOND = 200, INSUFFICIENT_GOLD = 201, INSUFFICIENT_SP = 202, 
}

ServerMsgId = {
  SERVER_MSG_ID_NONE = 0, WORLD_TO_MASTER_REGISTERED = 1, WORLD_TO_MASTER_UNREGISTERED = 2, 
  WORLD_TO_MASTER_REFRESH = 3, LOGIN_TO_MASTER_REGISTERED = 4, LOGIN_TO_MASTER_UNREGISTERED = 5, 
  LOGIN_TO_MASTER_REFRESH = 6, PROXY_TO_WORLD_REGISTERED = 7, PROXY_TO_WORLD_UNREGISTERED = 8, 
  PROXY_TO_WORLD_REFRESH = 9, PROXY_TO_GAME_REGISTERED = 10, PROXY_TO_GAME_UNREGISTERED = 11, 
  PROXY_TO_GAME_REFRESH = 12, GAME_TO_WORLD_REGISTERED = 13, GAME_TO_WORLD_UNREGISTERED = 14, 
  GAME_TO_WORLD_REFRESH = 15, DB_TO_WORLD_REGISTERED = 16, DB_TO_WORLD_UNREGISTERED = 17, 
  DB_TO_WORLD_REFRESH = 18, PVP_MANAGER_TO_WORLD_REGISTERED = 19, 
  PVP_MANAGER_TO_WORLD_UNREGISTERED = 20, PVP_MANAGER_TO_WORLD_REFRESH = 21, 
  PVP_MANAGER_TO_GAME_REGISTERED = 22, PVP_MANAGER_TO_GAME_UNREGISTERED = 23, 
  PVP_MANAGER_TO_GAME_REFRESH = 24, REQ_PVP_INSTANCE_CREATE = 30, ACK_PVP_INSTANCE_CREATE = 31, 
  REQ_PVP_INSTANCE_DESTROY = 32, ACK_PVP_INSTANCE_DESTROY = 33, REQ_PVP_INSTANCE_STATUS = 34, 
  ACK_PVP_INSTANCE_STATUS = 35, REQ_PVP_INSTANCE_LIST = 36, ACK_PVP_INSTANCE_LIST = 37, 
  REQ_PVP_STATUS = 50, ACK_PVP_STATUS = 51, REQ_PVP_GAME_INIT = 52, ACK_PVP_GAME_INIT = 53, 
  REQ_PLAYER_INFO = 54, ACK_PLAYER_INFO = 55, ACK_NEW_PLAYER = 56, REQ_CONNECT_GAME_SERVER = 60, 
  ACK_CONNECT_GAME_SERVER = 61, 
}

EGameMsgID = {
  UNKNOW = 0, EVENT_RESULT = 1, EVENT_TRANSPORT = 2, CLOSE_SOCKET = 3, STS_NET_INFO = 70, 
  REQ_LAG_TEST = 80, ACK_GATE_LAG_TEST = 81, ACK_GAME_LAG_TEST = 82, STS_SERVER_REPORT = 90, 
  STS_HEART_BEAT = 100, REQ_LOGIN = 101, ACK_LOGIN = 102, REQ_LOGOUT = 103, REQ_WORLD_LIST = 110, 
  ACK_WORLD_LIST = 111, REQ_CONNECT_WORLD = 112, ACK_CONNECT_WORLD = 113, 
  REQ_KICKED_FROM_WORLD = 114, REQ_CONNECT_KEY = 120, ACK_CONNECT_KEY = 122, 
  REQ_SELECT_SERVER = 130, ACK_SELECT_SERVER = 131, REQ_ROLE_LIST = 132, ACK_ROLE_LIST = 133, 
  REQ_CREATE_ROLE = 134, REQ_DELETE_ROLE = 135, REQ_RECOVER_ROLE = 136, REQ_LOAD_ROLE_DATA = 140, 
  ACK_LOAD_ROLE_DATA = 141, REQ_SAVE_ROLE_DATA = 142, ACK_SAVE_ROLE_DATA = 143, 
  REQ_ENTER_GAME = 150, ACK_ENTER_GAME = 151, REQ_LEAVE_GAME = 152, ACK_LEAVE_GAME = 153, 
  REQ_ENTER_GAME_FINISH = 154, ACK_ENTER_GAME_FINISH = 155, REQ_ENTER_SCENE = 160, 
  ACK_ENTER_SCENE = 161, REQ_LEAVE_SCENE = 162, ACK_LEAVE_SCENE = 163, 
  REQ_ENTER_SCENE_FINISH = 164, ACK_ENTER_SCENE_FINISH = 165, REQ_SWAP_SCENE = 170, 
  ACK_SWAP_SCENE = 171, REQ_SWAP_HOME_SCENE = 172, ACK_SWAP_HOME_SCENE = 173, 
  ACK_OBJECT_ENTRY = 200, ACK_OBJECT_LEAVE = 201, ACK_OBJECT_PROPERTY_ENTRY = 202, 
  ACK_OBJECT_RECORD_ENTRY = 203, ACK_PROPERTY_INT = 210, ACK_PROPERTY_FLOAT = 211, 
  ACK_PROPERTY_STRING = 212, ACK_PROPERTY_OBJECT = 214, ACK_PROPERTY_VECTOR2 = 215, 
  ACK_PROPERTY_VECTOR3 = 216, ACK_PROPERTY_CLEAR = 217, ACK_ADD_ROW = 220, ACK_REMOVE_ROW = 221, 
  ACK_SWAP_ROW = 222, ACK_RECORD_INT = 223, ACK_RECORD_FLOAT = 224, ACK_RECORD_STRING = 226, 
  ACK_RECORD_OBJECT = 227, ACK_RECORD_VECTOR2 = 228, ACK_RECORD_VECTOR3 = 229, 
  ACK_RECORD_CLEAR = 250, ACK_RECORD_SORT = 251, ACK_DATA_FINISHED = 260, REQ_MOVE = 300, 
  ACK_MOVE = 301, REQ_CHAT = 350, ACK_CHAT = 351, REQ_SKILL_OBJECTX = 400, 
  ACK_SKILL_OBJECTX = 401, REQ_SKILL_POS = 402, ACK_SKILL_POS = 403, ACK_ONLINE_NOTIFY = 600, 
  ACK_OFFLINE_NOTIFY = 601, REQ_ROOM_CREATE = 1000, ACK_ROOM_CREATE = 1001, 
  REQ_ROOM_DETAILS = 1002, ACK_ROOM_DETAILS = 1003, REQ_ROOM_JOIN = 1004, ACK_ROOM_JOIN = 1005, 
  ACK_ROOM_JOIN_NOTICE = 1006, REQ_ROOM_QUIT = 1007, ACK_ROOM_QUIT = 1008, 
  ACK_ROOM_QUIT_NOTICE = 1009, REQ_ROOM_LIST = 1010, ACK_ROOM_LIST = 1011, 
  REQ_ROOM_PLAYER_EVENT = 1020, ACK_ROOM_PLAYER_EVENT = 1021, REQ_START_PVP_GAME = 1032, 
  ACK_START_PVP_GAME = 1033, REQ_JOIN_PVP_GAME = 1034, ACK_JOIN_PVP_GAME = 1035, 
  REQ_QUIT_PVP_GAME = 1036, ACK_QUIT_PVP_GAME = 1037, ACK_PVP_GAME_OVER = 1038, 
}

EItemType = {
  EIT_EQUIP = 0, EIT_GEM = 1, EIT_SUPPLY = 2, EIT_SCROLL = 3, 
}

ESkillType = {
  BRIEF_SINGLE_SKILL = 0, BRIEF_GROUP_SKILL = 1, BULLET_SINGLE_SKILL = 2, 
  BULLET_REBOUND_SKILL = 3, BULLET_TARGET_BOMB_SKILL = 4, BULLET_POS_BOMB_SKILL = 5, 
  FUNC_SKILL = 6, 
}

ESceneType = {
  NORMAL_SCENE = 0, SINGLE_CLONE_SCENE = 1, MULTI_CLONE_SCENE = 2, 
}

ENPCType = {
  NORMAL_NPC = 0, HERO_NPC = 1, TURRET_NPC = 2, FUNC_NPC = 3, 
}

EServerState = {
  EST_CRASH = 0, EST_NARMAL = 1, EST_BUSY = 2, EST_FIRE = 3, EST_MAINTEN = 4, 
}

ELoginMode = {
  ELM_LOGIN = 0, ELM_REGISTER = 1, ELM_AUTO_REGISTER_LOGIN = 2, 
}

ReqServerListType = {
  RSLT_WORLD_SERVER = 0, RSLT_GAMES_ERVER = 1, 
}

ServerType = {
  SQUICK_ST_NONE = 0, SQUICK_ST_REDIS = 1, SQUICK_ST_MYSQL = 2, SQUICK_ST_MASTER = 3, 
  SQUICK_ST_LOGIN = 4, SQUICK_ST_PROXY = 5, SQUICK_ST_GAME = 6, SQUICK_ST_WORLD = 7, 
  SQUICK_ST_DB = 8, SQUICK_ST_MAX = 9, SQUICK_ST_GATEWAY = 10, SQUICK_ST_PVP_MANAGER = 11, 
  SQUICK_ST_MICRO = 12, 
}

EMoveType = {
  EMT_WALK = 0, EET_SPEEDY = 1, EET_TELEPORT = 2, 
}

EResultType = {
  EET_FAIL = 0, EET_SUCCESS = 1, EET_REFUSE = 2, EET_MISS = 3, EET_CRIT = 4, EET_ULTI = 5, 
}

EGameChatChannel = {
  EGCC_GLOBAL = 0, EGCC_CLAN = 1, EGCC_ROOM = 2, EGCC_TEAM = 3, 
}

EGameChatType = {
  EGCT_TEXT = 0, EGCT_VOICE = 1, EGCT_EMOJI = 2, 
}

RoomStatus = {
  ROOM_PLAYERS_PREPARE = 0, ROOM_PLAYERS_GAME = 1, 
}

